# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    environment:
      - URL=http://localhost:8080/swagger.json
  zacks:
    image: docker.io/iadolgov/zacks
    ports:
      - 8080:8080
    environment:
      SERVER_PORT: 8080
      CACHE_ENABLED: 1
      DBCACHE_ENABLED: 1
      DBCACHE_MONGODB_URL: mongodb://localhost:27017
      DBCACHE_MONGODB_DATABASE_NAME: zacks
      FETCHER_ENABLED: 1
      FETCHER_TIMEOUT_SECONDS: 10
      REFRESHER_ENABLED: 1
      REFRESHER_RESCAN_SECONDS: 3600
networks:
  default:
